### ISSUE TITLE
FHS

### ISSUE THREAD

**Issue by Hi-moor** [redhat-developer/rpm-packaging-guide#11]
What is an FHS?  Many thanks.

> Command or series of commands used to actually install the various artifacts into a resulting location in the FHS. Something to note is that this is done within the relative context of the %buildroot (more on that later).

--

**Comment by sghosh151** [comment]
FHS is File System Hierarchy. https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard

**Comment by xsuchy** [comment]
Link has been provided for community version.
 See https://github.com/redhat-developer/rpm-packaging-guide/blame/master/source/preparing-software.adoc#L493

**Comment by Hi-moor** [comment]
Thank you very much!
