### ISSUE TITLE
Add section "Custom macros"

### ISSUE THREAD

**Issue by xsuchy** [redhat-developer/rpm-packaging-guide#18]
I propose to add a new chapter about custom or user-defined macros.
Likely between "RPM Distribution Macros" and "Epoch, Scriptlets, and Triggers".
In next comment, I will propose the content.

**Comment by xsuchy** [comment]
User-defined macros
=================

You can override distribution macros in file `~/.rpmmacros`. Any change made will affect all build on your machine.

There are several macros which have the sense to override there:

`%_topdir /opt/some/working/directory/rpmbuild`
This is a directory where all builds are happening and utility `rpmdev-setuptree` can create it, including all subdirectories. By default, the value of this macro is `~/rpmbuild`. If for some reason, you want to have it located somewhere else, then this is the right place to change it.

`%_smp_mflags -l3`
This macro is very often to pass to Makefile e.g., `make %{?_smp_mflags}` and set number of concurrent processes during the build phase. By default, it is set to -jX where X is a number of cores. If you alter it here, you can speed up (or slow down) build of packages.

While you can define there new macros as well. This is discouraged, as these macros will not be present on other machines, where someone will try to rebuild your package.

**Comment by Daskyleia** [comment]
This section has been already added.
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/rpm_packaging_guide/advanced-topics#custom-macros
