### ISSUE TITLE
Not using PDF builds?

### ISSUE THREAD

**Issue by rkratky** [redhat-developer/rpm-packaging-guide#22]
https://github.com/redhat-developer/rpm-packaging-guide/blob/06fb01cec2e1f7bb8331cc272696c7c0954b6055/.travis.yml#L30

I see you're building the doc in PDF, too, but then you're not publishing it to GH pages. Maybe you can disable the PDF builds?

**Comment by pmkovar** [comment]
Good catch. I've fixed it in travis config, so we now provide a pdf here:

https://rpm-packaging-guide.github.io/rpm-packaging-guide.pdf
