### ISSUE TITLE
Suggested edit: %global preferred over %define

### ISSUE THREAD

**Issue by medington** [redhat-developer/rpm-packaging-guide#8]
In one of the [Fedora Packaging Guidelines](https://fedoraproject.org/wiki/Packaging:Guidelines?rd=Packaging/Guidelines#.25global_preferred_over_.25define) it's mentoned to use `%global` instead of `%define` (pasted below for refence). _Should this doc reflect that in the appendix?_

On a side note, the link in that section (http://rpm.org/wiki/Docs) 404s for me.

>  %global preferred over %define
> 
> Use %global instead of %define, unless you really need only locally defined submacros within other macro definitions (a very rare case).
> Rationale: The two macro defining statements behave the same when they are a the top level of rpm's nesting level.
> But when they are used in nested macro expansions (like in  %{!?foo: ... } constructs, %define theoretically only lasts until the end brace (local scope), while %global definitions have global scope.
> Note that %define and %global differ in more ways than just scope: the body of a %define'd macro is lazily expanded (ie when used), but the body of %global is expanded at definition time. It's possible to use %%-escaping to force lazy expansion of %global.
>

**Comment by Daskyleia** [comment]
Changes pull requested in #45
